version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poc-find-idle"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10ziytzq60hp8"
s3_prefix = "poc-find-idle"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
